#a-blatio ablatio
#a-caedo acide
#a-cieo acieris
#a-cieo acies
#a-cio acieris
#a-cio acies
#a-co acor
#a-conitor aconiti
#a-credo acredo
#a-creo#1 acra
#a-creo#1 acro
#a-creo#1 acror
#a-do ador
#a-do#2 ador
#a-edo#2 aedes
#a-edo#2 aedis
#a-equito aequitas
#a-equito aequiter
#a-eripio aeripes
#a-erugo#1 aerugo
#a-evito#1 aevitas
#a-jugo#1 ajuga
#a-laudo alauda
#a-ligo#1 aliger
#a-linquo aliqui
#a-lio alia
#a-lio alias
#a-lio alio
#a-liqueo aliqui
#a-liquo aliqua
#a-liquo aliquando
#a-liquo aliquanto
#a-liquo aliquo
#a-lito aliter
#a-lituro alitura
#a-luto#1 aluta
#a-marito amaritas
#a-marito amariter
#a-meto ametor
#a-meto#2 ametor
#a-metor ametor
#a-miceo amice
#a-nancio anancitis
#a-palo apala
#a-palo#1 apala
#a-palo#2 apala
#a-pico apica
#a-pio apio
#a-plano aplanes
#a-quatio aquatio
#a-reno#1 arena
#a-ruro arura
#a-strigo astriger
#a-ululo aulula
#a-uro auris
#a-uto autor
#a-utor autor
#a-vento aventer
#a-video avide
#a-vio avia
#a-volo avis
#ab-arceo abarcet
#ab-beo abba
#ab-beo abbas
#ab-emo abemito
#ab-grego abgregare
#ab-hiemo abhiemo
#ab-luto#1 ablutor
#ab-struo abstruo
#ab-torqueo abtorqueo
#ad-arceo adarce
#ad-cano accano
#ad-ducto adductor
#ad-finio affinis
#ad-fluento affluenter
#ad-gestio#2 aggestio
#ad-jacio adicio
#ad-livesco allivescit
#ad-monito admonitor
#ad-nasco adnascor
#ad-nasco annascor
#ad-nascor annascor
#ad-nato adnato
#ad-necto adnecto
#ad-neo#1 anne
#ad-niteo adnitendus
#ad-parito apparitor
#ad-penso appensor
#ad-saturo assatura
#ad-sedo assedo
#ad-uto adutor
#ad-utor adutor
#amb-ago ambages
#amb-ago ambago
#amb-ito ambitor
#ante-ago anteago
#ante-ambulo anteambulo
#ante-cesso antecessor
#ante-curso antecursor
#ante-dico#1 antedico
#ante-dico#2 antedico
#ante-paro#1 anteparo
#ante-paro#2 anteparo
#ante-po antepes
#ante-rideo anterides
#circum-colo#2 circumcola
#circum-ducto circumductor
#circum-fosso circumfossor
#circum-ito circuitor
#circum-tondeo circumtondeo
#circum-tremo circumtremo
#circum-vento circumventor
#co-adjuto coadjutor
#co-adjutor#1 coadjutor
#co-cio cocio
#co-co coco
#co-do coda
#co-do#2 coda
#co-eno coena
#co-liceo#1 colice
#co-liceor colice
#co-lineo colina
#co-lio colias
#co-miceo comice
#co-po copa
#co-po copo
#co-stabilio costabilis
#co-sto costa
#con-caedo concaedes
#con-capio#1 concapit
#con-clavo conclavo
#con-colo#1 concolor
#con-colo#2 concolor
#con-cubito concubitor
#con-decurio#1 condecurio
#con-denseo condenseo
#con-ducto conductor
#con-facio confacio
#con-fero conferte
#con-feto confeta
#con-fibulo confibula
#con-finio confinis
#con-flato conflator
#con-fugo confuga
#con-gestio#2 congestio
#con-lecto collector
#con-lego#1 collega
#con-monito commonitor
#con-munito communiter
#con-nitor#1 connitor
#con-pedo#1 compedes
#con-pedo#2 compedes
#con-poto compotor
#con-rugio corrugis
#con-satio#1 consatio
#con-sitio consitio
#con-solido consolida
#con-sortio consortio
#con-sortior consortio
#con-specto conspector
#con-sponso consponsor
#con-sum#1 consum
#con-tago contages
#con-tento contemptor
#con-torto contortor
#de-calceo decalco
#de-calco decalco
#de-calefacio decalefacio
#de-calesco decalesco
#de-cesso decessor
#de-cieo decies
#de-cio decies
#de-co decas
#de-co deceris
#de-co decor
#de-curo decures
#de-ducto deductor
#de-fio defio
#de-forio deforis
#de-indo deinde
#de-ito deitas
#de-jugo#2 dejugis
#de-lanio#1 delaniare
#de-lito delitor
#de-meio demeio
#de-pacisco depaciscor
#de-potio#2 depotitur
#de-potior#1 depotitur
#de-prenso deprensa
#de-pulpo depulpo
#de-queo deque
#de-spico despica
#de-sponso desponsor
#de-supo desuper
#de-tento detentor
#dis-colo#1 discolor
#dis-colo#2 discolor
#dis-gestio#2 digestio
#dis-gnosco dignosco
#dis-lecto dilector
#dis-neo#1 dine
#dis-partior dispartio
#dis-repto direptor
#dis-tracto distractor
#dis-viso divisor
#dis-vitio divitia
#ex-consulo exconsularis
#ex-cubito excubitor
#ex-dito editor
#ex-ducto eductor
#ex-edo exesto
#ex-fio effio
#ex-gestio#2 egestio
#ex-lateo elate
#ex-latito elatites
#ex-laudo elaudare
#ex-liceo#1 elices
#ex-liceor elices
#ex-plico explicate
#ex-presso expressor
#ex-reor eremus
#ex-reor eres
#ex-repto ereptor
#ex-rogo exrogare
#ex-sector#2 exsector
#ex-torto extortor
#ex-tremo extremo
#ex-ungo exungo
#in-acerbo inacerbo
#in-auspico inauspicato
#in-beo imber
#in-calo incalanto
#in-censeo incense
#in-censeo#1 incense
#in-comito incomitem
#in-comito incomiter
#in-comitor incomiter
#in-commeo incomma
#in-communio#1 incommunis
#in-como#1 incomis
#in-credo incredendus
#in-credo incredundus
#in-doleo indoles
#in-dolo#1 indoles
#in-ducto inductor
#in-fateor infiteri
#in-for infandus
#in-for infer
#in-for inferne
#in-frequento infrequenter
#in-gestio#2 ingestio
#in-humano inhumano
#in-jugo#2 injugis
#in-merito#2 immerito
#in-mobilito immobilitas
#in-munito immunitas
#in-orior inorior
#in-orior inoris
#in-paeniteo impaenitendus
#in-parento imparentem
#in-parito impariter
#in-pasco impascor
#in-pascor impascor
#in-pigreo impigre
#in-po impes
#in-provideo improvide
#in-proviso#2 improviso
#in-pulso impulsor
#in-punior impunis
#in-saluto insalutaris
#in-similo insimilo
#in-sitio insitio
#in-somnio insomnia
#in-supo insuper
#in-temero intemerandus
#in-termino intermino
#in-testo intestato
#in-timeo intime
#in-tuto intuta
#in-tuto#2 intuta
#in-unguo inunguo
#in-vecto invector
#in-vento inventor
#inter-amento interamenta
#inter-aperio interaperio
#inter-caedo intercisi
#inter-cesso intercessor
#inter-dicto interdictor
#inter-do#2 interdo
#inter-edo interest
#inter-facio interfacio
#inter-mino intermino
#inter-neo#1 interne
#inter-no#1 interna
#inter-no#1 internas
#inter-polio#1 interpolis
#inter-trituro intertritura
#inter-vento interventor
#ob-acerbo obacerbat
#ob-caedo occaedes
#ob-esco obescet
#ob-esito obesitas
#ob-flo offla
#ob-for offa
#ob-herbesco obherbescere
#ob-ito obiter
#ob-liqueo oblique
#ob-lito oblitor
#ob-necto obnectere
#ob-presso oppressor
#ob-saluto obsalutare
#ob-stupeo obstupendus
#ob-tracto obtractat
#per-audio peraudiendus
#per-celo perceler
#per-cerno percernis
#per-como#1 percomis
#per-dito perditor
#per-domito perdomitor
#per-excrucio perexcrucio
#per-exilio perexilis
#per-extimesco perextimesco
#per-fosso perfossor
#per-fugo perfuga
#per-grandio pergrandis
#per-indo perinde
#per-insignio perinsignis
#per-miro permirandus
#per-miror permirandus
#per-mollio permollis
#per-multo#2 permulto
#per-no#1 perna
#per-opto peroptato
#per-po perpes
#per-taedeo pertaedeo
#per-ungo perungo
#per-valeo pervaleo
#per-vecto pervector
#per-vento perventor
#prae-celo praeceler
#prae-cesso praecessor
#prae-co praeco
#prae-curso praecursor
#prae-grandio praegrandis
#prae-lecto praelector
#prae-monito praemonitor
#prae-po praepes
#prae-repto praereptor
#prae-stabilio praestabilis
#prae-ungo praeungo
#prae-varico praevarico
#prae-vento praeventor
#praeter-ito praeterita
#pro-aucto proauctor
#pro-calo procalare
#pro-capio#1 procapis
#pro-cero proceres
#pro-cito#2 procitant
#pro-cito#2 procitare
#pro-co proceres
#pro-consulo proconsularis
#pro-dito proditor
#pro-fateor profiteor
#pro-fluento profluenter
#pro-fugo profuga
#pro-fundito profunditas
#pro-mello promellere
#pro-monstro promonstra
#pro-neo#1 prone
#pro-plasmo proplasma
#pro-po propes
#pro-polio#1 propolis
#pro-reto proreta
#pro-rigo proriga
#pro-sapio prosapies
#pro-sector#2 prosector
#pro-sedo proseda
#pro-sopio prosopis
#pro-spico prospica
#pro-sumo prosumo
#pro-vecto provector
#prod-ito proditor
#re-claudo reclaudo
#re-fero refero
#re-fugo refuga
#re-galeo regales
#re-moro remores
#re-nancio renancitur
#re-nancior renancitur
#re-po repandus
#re-presso repressor
#re-socio resociandus
#re-sum#1 resum
#re-tero retero
#re-tero retero
#re-vereor reverendus
#re-vero revera
#red-dito redditor
#se-caleo secale
#se-co secundae
#se-co secundum
#se-curito securitas
#se-ducto seductor
#se-lecto selector
#se-lenio selenitis
#se-libro selibra
#se-lineo selinas
#se-mentior sementis
#se-meo semet
#se-nato senator
#se-pio sepia
#se-rapio serapias
#se-reneo serene
#se-rivo seriva
#se-simo#1 sesima
#sub-adjuvo subadjuva
#sub-alo subalare
#sub-alo subalaris
#sub-cesso successor
#sub-co succo
#sub-curso succursor
#sub-doleo subdole
#sub-for suffes
#sub-gestio#2 suggestio
#sub-grandio suggrandis
#sub-inanio subinanis
#sub-influo subinfluo
#sub-lateo sublate
#sub-limito sublimitas
#sub-limito sublimiter
#sub-malo summalis
#sub-meo summa
#sub-meo summas
#sub-minio#1 summinia
#sub-moto summotor
#sub-oculo subocularis
#sub-presso suppressor
#sub-sipo subsipere
#sub-vado#1 subvades
#sub-vado#2 subvades
#super-facio superficies
#super-gradior supergradior
#super-intento superintentor
#super-molo#1 supermolaris
#super-neo#1 superne
#super-no#1 supernas
#super-vacuo supervacuo
#trans-dito traditor
#trans-ducto traductor
#trans-fugo transfuga
#trans-ito transitor
#trans-sitio transitio
#trans-supplodo transsero
a-dedo adedo
a-dito adito
a-piscor apiscor
a-specio aspicio
a-spicio aspicio
a-spiro aspiro
ab-caedo abcido
ab-do abdo
ab-do#2 abdo
ab-eo#1 abeo
ab-horreo abhorreo
ab-jacio abicio
ab-oleo#1 aboleo
ab-repo arrepo
ab-rumpo abrumpo
ab-sum#1 absum
ab-uto abutor
ab-utor abutor
abs-sum#1 absum
abs-teneo abstineo
ad-aperio adaperio
ad-augeo adaugeo
ad-clamito acclamito
ad-colo#1 accolo
ad-colo#2 accolo
ad-congero#1 accongero
ad-decet addecet
ad-edo adedo
ad-edo#2 adedo
ad-eo#1 adeo#1
ad-expeto adexpeto
ad-facio afficio
ad-fero affero
ad-figo affigo
ad-flecto afflecto
ad-fligo affligo
ad-flo afflo
ad-for affor
ad-frico affrico
ad-fulgeo affulgeo
ad-fundo#1 affundo
ad-fundo#2 affundo
ad-gnosco agnosco
ad-gradior aggredior
ad-habito adhabito
ad-horreo adhorreo
ad-indo adindo
ad-ito adito
ad-jubeo adjubeo
ad-labor#1 allabor
ad-lambo allambo
ad-loquor alloquor
ad-nascor agnascor
ad-navigo adnavigo
ad-nitor#1 annitor
ad-no#1 anno#1
ad-nosco agnosco
ad-opino adopinor
ad-opinor adopinor
ad-pareo appareo
ad-pendo appendo
ad-plaudo applaudo
ad-plico applico
ad-plodo applaudo
ad-pono appono
ad-porto apporto
ad-prehendo apprehendo
ad-propero appropero
ad-propinquo appropinquo
ad-quaero acquiro
ad-quiesco acquiesco
ad-repo arrepo
ad-salio#2 assilio
ad-scribo ascribo
ad-sector#2 assector
ad-sisto assisto
ad-soleo assoleo
ad-spiro aspiro
ad-sto asto
ad-stringo astringo
ad-suesco assuesco
ad-sum#1 adsum
ad-surgo assurgo
ad-tribulo attribulo
ad-tribuo attribuo
ad-vereor advereor
amb-edo ambedo
amb-edo#2 ambedo
ante-eo#1 anteeo
ante-fero antefero
as-spiro aspiro
circum-do circumdo
circum-do#2 circumdo
circum-eo#1 circumeo
circum-fero circumfero
circum-fodio circumfodio
circum-gradior circumgredior
circum-jaceo circumjaceo
circum-jacio circumicio
circum-lavo circumlavo
circum-linio circumlinio
circum-loquor circumloquor
circum-salio#2 circumsilio
circum-sedeo circumsedeo
circum-specio circumspicio
co-alesco coalesco
co-aresco coaresco
co-eo#1 coeo
co-uto coutor
co-utor coutor
con-cateno concateno
con-comito concomitor
con-comitor concomitor
con-cubo concubo
con-custodio concustodio
con-decet condecet
con-eo#1 coeo
con-fabrico confabricor
con-fabricor confabricor
con-fabulo confabulor
con-fabulor confabulor
con-fero confero
con-fervesco confervesco
con-figuro configuro
con-fio conficio
con-foedero confoedero
con-frequento confrequento
con-frio confrio
con-gratulor congratulor
con-jacio conicio
con-labor#1 collabor
con-libet collibet
con-libo#1 collibet
con-luceo colluceo
con-necto conecto
con-nitor#1 conitor
con-pluo compluit
con-preco comprecor
con-precor comprecor
con-prehendo comprehendo
con-quaero conquiro
con-rugo corrugo
con-sacro consecro
con-saepio consaepio
con-scindo conscindo
con-sepelio consepelio
con-solido consolido
con-sopio consopio
con-spargo#1 conspergo
con-spuo conspuo
con-spurco conspurco
con-subigo consubigo
con-sueo consueo
con-temero contemero
con-tero contero
con-tono contonat
con-torqueo contorqueo
con-tribulo contribulo
con-tueo contueor
con-tueor contueor
con-vesco convescor
con-vitio convitio
con-voveo convoveo
con-vulnero convulnero
de-ambulo deambulo
de-armo dearmo
de-carmino#1 decarmino
de-carmino#2 decarmino
de-curro decurro
de-curto decurto
de-duco deduco
de-eo#1 deeo
de-erro#1 deerro
de-fatisco defetiscor
de-fero defero
de-fraudo defraudo
de-fremo defremo
de-frico defrico
de-fruor defruor
de-fungor defungor
de-glabro deglabro
de-glubo deglubo
de-grandino degrandinat
de-gravo degravo
de-grunnio digrunnio
de-hisco dehisco
de-jacio deicio
de-lavo delavo
de-libro delibro
de-liquo deliquo
de-mordeo demordeo
de-moveo demoveo
de-nasco denascor
de-nascor denascor
de-operio deoperio
de-paciscor depeciscor
de-pango depango
de-pecto depecto
de-pleo depleo
de-polio#1 depolio
de-promo depromo
de-pudeo depudet
de-purgo depurgo
de-saevio desaevio
de-salio#2 desilio
de-sicco desicco
de-signo designo
de-spicio despicio
de-sugo desugo
de-sum#1 desum
de-tendo detendo
de-torno detorno
de-uto deutor
de-utor deutor
de-vasto devasto
de-vello devello
de-vesco devescor
dis-bucino dibucino
dis-crucio discrucio
dis-fateor diffiteor
dis-fero differo
dis-fido diffido
dis-findo diffindo
dis-lorico dilorico
dis-moveo dimoveo
dis-nosco dinosco
dis-pando#1 dispando
dis-pando#2 dispando
dis-partio#2 dispertio
dis-pergo dispergo
dis-plodo displodo
dis-po dispando
dis-pono dispono
dis-pudeo dispudet
dis-rapio diripio
dis-rego dirigo
dis-rigo dirigo
dis-rumpo dirumpo
dis-seco disseco
dis-sipo dissipo
dis-suo dissuo
dis-taedet distaedet
ec-freno effreno
ex-cieo excio
ex-creo#1 exscreo
ex-dico#2 edico
ex-edo exedo
ex-edo#2 exedo
ex-eo#1 exeo
ex-fero effero#1
ex-fervesco effervesco
ex-fleo effleo
ex-fodio effodio
ex-freno effreno
ex-frico effrico
ex-gurgito egurgito
ex-jacio eicio
ex-labo elabor
ex-labor#1 elabor
ex-marcesco emarcesco
ex-molio emolior
ex-molior emolior
ex-molo#1 emolo
ex-moveo emoveo
ex-nasco enascor
ex-nascor enascor
ex-neco eneco
ex-nitesco enitesco
ex-nitor#1 enitor
ex-notesco enotesco
ex-ordior exordior
ex-orior exorior
ex-patior exspatior
ex-plico explico
ex-pungo expungo
ex-rapio eripio
ex-ruo eruo
ex-salio#2 exsilio
ex-scindo exscindo
ex-seco exseco
ex-spargo#1 exspergo
ex-stinguo exstinguo
ex-video evideor
in-aresco inaresco
in-assero#1 inassero
in-assero#2 inassero
in-audio inaudio
in-cohibeo incohibeo
in-cresco incresco
in-cubo incubo#1
in-eo#1 ineo
in-fatigo infatigo
in-fero infero
in-flecto inflecto
in-fligo infligo
in-generasco ingenerasco
in-gradior ingredior
in-ludo illudo
in-obscuro inobscuro
in-plico implico
in-rado irrado
in-rideo irrideo
in-rumpo irrumpo
in-saepio insaepio
in-salio#2 insilio
in-signo insigno
in-sum#1 insum
in-urgeo inurgeo
in-vilito invilito
in-violo inviolo
inter-calceo interculco
inter-calco interculco
inter-do interdo
inter-emo interimo
inter-eo#1 intereo
inter-fio interfio
inter-fugio interfugio
inter-fundo interfundo
inter-lucesco interlucesco
inter-premo interprimo
inter-sum#1 intersum
intro-eo#1 introeo
ob-cano occano
ob-coepio occipio
ob-curro occurro
ob-duco obduco
ob-dulcesco obdulcesco
ob-edo obedo
ob-edo#2 obedo
ob-eo#1 obeo
ob-facio officio
ob-fero offero
ob-fuco offoco
ob-fundo#1 offundo
ob-fundo#2 offundo
ob-irasco obirascor
ob-irascor obirascor
ob-jurgo objurgo
ob-lineo oblino
ob-linio oblinio
ob-nitor#1 obnitor
ob-pango oppango
ob-porto opporto
ob-ruo obruo
ob-servio observito
ob-sto obsto
ob-stupesco obstipesco
ob-sum#1 obsum
ob-torpeo obtorpeo
ob-tueo obtueor
ob-tueor obtueor
ob-violo obviolo
op-fero offero
op-pango oppango
op-pingo oppango
op-pono oppono
per-aresco peraresco
per-caedo percaedo
per-cedo#1 percedo
per-clamo perclamo
per-cludo percludo
per-cupio percupio
per-domo perdomo
per-eo#1 pereo
per-fero perfero
per-fingo perfingo
per-frico perfrico
per-frigeo perfrigeo
per-fungor perfungor
per-libet perlibet
per-libo#1 perlibet
per-liceo#1 perlicet
per-liceor perlicet
per-lineo perlino
per-linio perlinio
per-lino perlino
per-moneo permoneo
per-morior permorior
per-moro permoror
per-moror#1 permoror
per-moror#2 permoror
per-narro pernarro
per-nosco pernosco
per-nuntio pernuntio
per-odi perodi
per-ploro perploro
per-salio#2 persilio
per-suo persuo
per-taedeo pertaedet
per-tumesco pertumesco
per-urgeo perurgeo
prae-acuo praeacuo
prae-aequo praeaequo
prae-carpo praecerpo
prae-coepio praecoepi
prae-crudesco praecrudesco
prae-eo#1 praeeo
prae-fero praefero
prae-gigno praegigno
prae-jacio praeicio
prae-oro praeoro
prae-ostendo praeostendo
prae-patior praepatior
prae-plecto#2 praeplecto
prae-possum praepossum
prae-propero praepropero
prae-sido praesidero
prae-specio praespicio
prae-spicio praespicio
prae-stinguo praestinguo
prae-sum#1 praesum
prae-suo praesuo
prae-tento praetento
prae-verno praevernat
praeter-ago praeterago
praeter-eo#1 praetereo
praeter-fero praeterfero
praeter-rado praeterrado
praeter-sum#1 praetersum
praeter-veho praetervehor
pro-creo#1 procreo
pro-emineo proemineo
pro-eo#1 prodeo
pro-fero profero
pro-geniculo progeniculo
pro-gigno progigno
pro-lugeo prolugeo
pro-mutuo promutuor
pro-mutuo#2 promutuor
pro-mutuor promutuor
pro-patior propatior
pro-purgo propurgo
pro-salio#2 prosilio
pro-specio prospicio
pro-vegeo provegeo
pro-vendo provendo
re-bullio rebullio
re-calefacio recalfacio
re-canto recanto
re-cingo recingo
re-claudo#1 recludo
re-claudo#2 recludo
re-creo#1 recreo
re-eo#1 redeo
re-fero refert
re-frico refrico
re-liceo#1 reliceor
re-liceor reliceor
re-lucesco relucesco
re-mundo remundo
re-nasco renascor
re-nascor renascor
re-nitor#1 renitor
re-operio redoperio
re-pecto repecto
re-salio#2 resilio
re-salvo resalvare
re-teneo retineo
re-vello revello
re-vereor revereor
re-vivesco revivisco
re-volvo revolvo
red-eo#1 redeo
retro-specio retrospicio
se-pio saepio
sub-aduno subaduno
sub-edo subedo
sub-edo#2 subedo
sub-eo#1 subeo
sub-erigo suberigo
sub-fero suffero
sub-irasco subirascor
sub-irascor subirascor
sub-lugeo sublugeo
sub-mitto summitto
sub-necto subnecto
sub-pedo#1 suppedo
sub-pedo#2 suppedo
sub-pudeo suppudet
sub-rapio surripio
sub-rego surgo
sub-ringor surringor
sub-ruo surruo
sub-sum#1 subsum
sub-uro suburo
sub-vereor subvereor
super-curro supercurro
super-effero#1 supereffero
super-effero#2 supereffero
super-egredior superegredior
super-emorior superemorior
super-fero superfero
super-figo superfigo
super-fio superfio
super-fugio superfugio
super-gradior supergredior
super-impleo superimpleo
super-inspicio superinspicio
super-labo superlabor
super-labor#1 superlabor
super-perspicio superperspicio
super-ruo superruo
super-stringo superstringo
super-sum#1 supersum
trans-duco traduco
trans-eo#1 transeo
trans-fero transfero
trans-jungo transjungo
trans-loquor traloquor
trans-moveo transmoveo
trans-salio#2 transilio
trans-sero#1 transero
trans-sero#2 transero
trans-sero#3 transero
trans-sumo transsumo
trans-vendo transvendo
